using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Nodes;
using static Village.Core.J;

namespace Village.Core;

/// <summary>Structural, cadastral, geometric and accessibility invariants for VillageMap v4.</summary>
public static class VillageValidation
{
    static readonly string[] ZoneTypes=["residential","commercial","craft","civic","agricultural"];
    static readonly (int bit,int opposite,int dx,int dy)[] Directions=[(1,4,0,-1),(2,8,1,0),(4,1,0,1),(8,2,-1,0)];
    static string Key(int x,int y)=>$"{x},{y}";
    static string Key(JsonNode? n)=>Key(I(n,"x"),I(n,"y"));
    static bool Integer(JsonNode? n)=>n is JsonValue&&double.IsFinite(Number(n))&&Number(n)==Math.Floor(Number(n));
    static bool Finite(JsonNode? n)=>n is JsonValue&&double.IsFinite(Number(n));
    static List<JsonNode> Items(JsonNode? n)=>n is JsonArray a?a.Where(x=>x!=null).Select(x=>x!).ToList():[];
    static JsonNode? At(JsonNode? n,int index)=>n is JsonArray a&&index>=0&&index<a.Count?a[index]:null;
    static string Text(JsonNode? n)=>n?.GetValue<string>()??"";
    static bool InBounds(JsonNode? n,int w,int h)=>n!=null&&Integer(n["x"])&&Integer(n["y"])&&I(n,"x")>=0&&I(n,"y")>=0&&I(n,"x")<w&&I(n,"y")<h;
    static Dictionary<string,JsonNode> ById(IEnumerable<JsonNode> nodes)=>nodes.GroupBy(n=>S(n,"id")).ToDictionary(g=>g.Key,g=>g.Last());
    static bool ContainsIndex(JsonNode? n,int index)=>Items(n).Any(x=>Number(x)==index);
    static double Distance(JsonNode? a,JsonNode? b,double offset=0)=>Math.Sqrt(Math.Pow(D(a,"x")-D(b,"x")-offset,2)+Math.Pow(D(a,"y")-D(b,"y")-offset,2));

    public static JsonObject Validate(JsonObject map,JsonArray catalog)
    {
        var errors=new List<string>();int w=I(map,"width"),h=I(map,"height");var roads=Items(map["roads"]);var buildings=Items(map["buildings"]);var props=Items(map["props"]);
        if(I(map,"schemaVersion")!=4)errors.Add("schemaVersion inválido");
        if(!Integer(map["width"])||w!=h)errors.Add("dimensões inválidas");
        if(map["terrain"] is not JsonArray terrain||terrain.Count!=w*h)errors.Add("camada de terreno incompleta");
        if(map["heightLevel"] is not JsonArray heights||heights.Count!=w*h)errors.Add("camada de altura incompleta");else if(heights.Any(n=>!Integer(n)||Number(n)<0||Number(n)>6))errors.Add("nível de altura fora de 0..6");
        string layout=S(map["settings"],"layout");if(layout=="grid"&&S(map,"roadTopology")!="orthogonal-cardinal")errors.Add("grade sem topologia ortogonal cardinal");if(layout=="organic"&&S(map,"roadTopology")!="organic-cardinal")errors.Add("traçado orgânico sem topologia declarada");
        Zones(map,errors);
        var roadAt=roads.GroupBy(Key).ToDictionary(g=>g.Key,g=>g.Last());var roadSet=roadAt.Keys.ToHashSet();if(roadSet.Count!=roads.Count)errors.Add("tiles de estrada duplicados");
        foreach(var r in roads)
        {
            string key=Key(r);int mask=I(r,"connections");bool water=Text(At(map["terrain"],I(r,"y")*w+I(r,"x")))=="water";
            if(!Integer(r["connections"])||mask<0||mask>15)errors.Add($"máscara viária inválida em {key}");
            foreach(var d in Directions)if((mask&d.bit)!=0&&(!roadAt.TryGetValue(Key(I(r,"x")+d.dx,I(r,"y")+d.dy),out var n)||(I(n,"connections")&d.opposite)==0))errors.Add($"conexão viária não recíproca em {key}");
            if(r["bridge"]==null||B(r,"bridge")!=water)errors.Add($"ponte inconsistente em {key}");if(B(r,"bridge")&&!((S(r,"orientation")=="ns"&&mask==5)||(S(r,"orientation")=="ew"&&mask==10)))errors.Add($"orientação de ponte inválida em {key}");if(!B(r,"bridge")&&(!r.AsObject().ContainsKey("orientation")||r["orientation"]!=null))errors.Add($"estrada terrestre com orientação de ponte em {key}");if(r["segmentIds"] is not JsonArray)errors.Add($"segmentIds inválido em {key}");
        }
        Bridges(map,roadAt,errors);Urban(map,roadAt,errors);
        var start=roads.FirstOrDefault(r=>S(r,"kind")=="plaza")??roads.FirstOrDefault();if(start==null)errors.Add("rede viária vazia");else{var reached=new HashSet<string>{Key(start)};var queue=new List<JsonNode>{start};for(int i=0;i<queue.Count;i++)foreach(var d in Directions){var r=queue[i];if((I(r,"connections")&d.bit)==0)continue;string key=Key(I(r,"x")+d.dx,I(r,"y")+d.dy);if(roadAt.TryGetValue(key,out var n)&&reached.Add(key))queue.Add(n);}if(reached.Count!=roadAt.Count)errors.Add($"rede viária desconectada: {roadAt.Count-reached.Count} tiles");}
        var spec=map["gridSpec"];if(layout!="grid"){if(spec!=null)errors.Add("traçado orgânico não deve expor gridSpec");}else if(spec==null||new[]{"centerX","centerY","spacing","radius"}.Any(k=>!Integer(spec[k]))||I(spec,"spacing")<12||I(spec,"spacing")>16||I(spec,"radius")<1)errors.Add("gridSpec inválido");else if(!roadSet.Contains(Key(I(spec,"centerX"),I(spec,"centerY"))))errors.Add("centro da grade sem rua");
        var (expanded,doors)=Buildings(map,roadAt,ById(Items(catalog)),errors);var occupied=new HashSet<string>();var trees=new List<JsonNode>();
        foreach(var p in props){string id=S(p,"id"),key=Key(p);int index=I(p,"y")*w+I(p,"x");if(!InBounds(p,w,h))errors.Add($"prop {id} fora do mapa");if(roadSet.Contains(key)||expanded.Contains(key))errors.Add($"prop {id} ocupa rua ou margem de edifício");if(doors.Contains(key))errors.Add($"prop {id} ocupa uma porta");if(Text(At(map["terrain"],index))=="water")errors.Add($"prop {id} sobre água");if(At(map["heightLevel"],index)==null||Number(At(map["heightLevel"],index))!=D(p,"level"))errors.Add($"nível incorreto em {id}");if(!occupied.Add(key))errors.Add($"props sobrepostos em {key}");if(S(p,"type") is "oak" or "pine" or "willow")trees.Add(p);}
        for(int i=0;i<trees.Count;i++)for(int j=i+1;j<trees.Count;j++)if(Math.Max(Math.Abs(I(trees[i],"x")-I(trees[j],"x")),Math.Abs(I(trees[i],"y")-I(trees[j],"y")))<=1)errors.Add($"árvores próximas demais: {S(trees[i],"id")} e {S(trees[j],"id")}");
        var range=S(map["settings"],"settlement") switch{"hamlet"=>(10,18),"village"=>(25,40),"town"=>(55,85),_=>(int.MaxValue,int.MinValue)};int houses=buildings.Count(b=>S(b,"type")=="house");if(houses<range.Item1||houses>range.Item2)errors.Add($"quantidade de casas fora da faixa: {houses}");return O("valid",errors.Count==0,"errors",A(errors));
    }
    static void Bridges(JsonObject map,Dictionary<string,JsonNode> roadAt,List<string> errors)
    {
        if(map["bridgeSpans"] is not JsonArray){errors.Add("bridgeSpans ausente");return;}var spans=Items(map["bridgeSpans"]);var byId=ById(spans);if(byId.Count!=spans.Count)errors.Add("IDs de bridgeSpans duplicados");var claimed=new HashSet<string>();
        foreach(var span in spans)
        {
            string id=S(span,"id"),axis=S(span,"axis");var indexes=Items(span["roadIndexes"]);if(axis is not("ew" or "ns")||span["roadIndexes"] is not JsonArray||I(span,"length")!=indexes.Count||indexes.Count<1){errors.Add($"bridgeSpan inválido: {id}");continue;}
            var roads=indexes.Select(i=>At(map["roads"],(int)Number(i))).ToList();int dx=axis=="ew"?1:0,dy=axis=="ns"?1:0;
            for(int i=0;i<roads.Count;i++){var r=roads[i];string role=roads.Count==1?"single":i==0?"start":i==roads.Count-1?"end":i%3==0?"post":"middle";if(r==null||!B(r,"bridge")||S(r,"orientation")!=axis||S(r,"bridgeSpanId")!=id||I(r,"bridgeIndex")!=i||S(r,"bridgeRole")!=role){errors.Add($"metadados de ponte inválidos em {id}:{i}");continue;}if(!claimed.Add(Key(r)))errors.Add($"tile de ponte duplicado em spans: {Key(r)}");if(i>0&&(I(r,"x")!=I(roads[i-1],"x")+dx||I(r,"y")!=I(roads[i-1],"y")+dy))errors.Add($"bridgeSpan não contínuo: {id}");}
            if(indexes.Count>(roads.Any(r=>S(r,"kind")=="main")?14:8))errors.Add($"bridgeSpan longo demais: {id}");
            foreach(var (label,point,edge,sign) in new[]{("entrada",span["entry"],roads[0],-1),("saída",span["exit"],roads[^1],1)})if(point==null||edge==null||I(point,"x")!=I(edge,"x")+dx*sign||I(point,"y")!=I(edge,"y")+dy*sign||!roadAt.TryGetValue(Key(point),out var dry)||B(dry,"bridge"))errors.Add($"{label} seca inválida em {id}");
        }
        foreach(var r in Items(map["roads"])){if(B(r,"bridge")&&(!byId.ContainsKey(S(r,"bridgeSpanId"))||!claimed.Contains(Key(r))))errors.Add($"ponte órfã em {Key(r)}");if(!B(r,"bridge")&&(r["bridgeSpanId"]!=null||r["bridgeRole"]!=null||r["bridgeIndex"]!=null))errors.Add($"metadados de ponte em terra em {Key(r)}");}
    }
    static void Zones(JsonObject map,List<string> errors)
    {
        int w=I(map,"width"),h=I(map,"height");if(map["zoneMap"] is not JsonArray layer||layer.Count!=w*h){errors.Add("camada de zoneamento incompleta");return;}if(layer.Any(z=>Text(z)!="none"&&!ZoneTypes.Contains(Text(z))))errors.Add("tipo de zona inválido na camada");if(map["zones"] is not JsonArray){errors.Add("metadados de zona ausentes");return;}var zones=Items(map["zones"]);if(zones.Count!=ZoneTypes.Length)errors.Add($"quantidade de zonas inválida: {zones.Count}");if(zones.Select(z=>S(z,"id")).Distinct().Count()!=zones.Count||zones.Select(z=>S(z,"type")).Distinct().Count()!=zones.Count)errors.Add("metadados de zona duplicados");
        for(int i=0;i<layer.Count;i++)if(Text(At(map["terrain"],i))=="water"&&Text(layer[i])!="none")errors.Add($"água zonificada no índice {i}");var roads=Items(map["roads"]);var dry=roads.Where(r=>!B(r,"bridge")).Select(Key).ToHashSet();
        foreach(string type in ZoneTypes)
        {
            var metadata=zones.FirstOrDefault(z=>S(z,"type")==type);if(metadata==null){errors.Add($"metadados ausentes para zona {type}");continue;}var cells=Enumerable.Range(0,layer.Count).Where(i=>Text(layer[i])==type).ToList();if(S(metadata,"id")!=$"zone-{type}"||I(metadata,"cellCount")!=cells.Count)errors.Add($"metadados inconsistentes para zona {type}");if(S(metadata,"label")=="")errors.Add($"label ausente para zona {type}");if(cells.Count==0){errors.Add($"zona {type} vazia");continue;}
            int minx=cells.Min(i=>i%w),maxx=cells.Max(i=>i%w),miny=cells.Min(i=>i/w),maxy=cells.Max(i=>i/w);var b=metadata["bounds"];if(b==null||I(b,"x")!=minx||I(b,"y")!=miny||I(b,"width")!=maxx-minx+1||I(b,"height")!=maxy-miny+1)errors.Add($"bounds inconsistentes para zona {type}");var anchor=metadata["anchor"];if(!InBounds(anchor,w,h))errors.Add($"anchor inválido para zona {type}");else{if(Text(layer[I(anchor,"y")*w+I(anchor,"x")])!=type)errors.Add($"anchor fora da zona {type}");if(!dry.Contains(Key(anchor)))errors.Add($"anchor da zona {type} sem rua terrestre");}
            var links=Items(metadata["bridgeLinks"]).Select(n=>(int)Number(n)).ToList();if(metadata["bridgeLinks"] is not JsonArray||links.Distinct().Count()!=links.Count)errors.Add($"bridgeLinks inválidos para zona {type}");foreach(int i in links){var r=roads.FirstOrDefault(r=>I(r,"y")*w+I(r,"x")==i);if(r==null||!B(r,"bridge")||Text(At(map["terrain"],i))!="water"||Text(At(layer,i))!="none")errors.Add($"bridgeLink inválido para zona {type}");}
            var remaining=cells.Concat(links).Concat(roads.Select(r=>I(r,"y")*w+I(r,"x"))).ToHashSet();var queue=new List<int>{cells[0]};remaining.Remove(cells[0]);for(int cursor=0;cursor<queue.Count;cursor++){int i=queue[cursor],x=i%w,y=i/w;foreach(var d in Directions){int nx=x+d.dx,ny=y+d.dy;if(nx>=0&&ny>=0&&nx<w&&ny<h&&remaining.Remove(ny*w+nx))queue.Add(ny*w+nx);}}int disconnected=remaining.Count(i=>Text(At(layer,i))==type);if(disconnected>0)errors.Add($"zona {type} desconectada: {disconnected} tiles");if(map["stats"]?["zoneCounts"] is JsonNode counts&&I(counts,type)!=cells.Count)errors.Add($"estatística divergente para zona {type}");
        }
        var plaza=map["plaza"];for(int y=I(plaza,"y");y<I(plaza,"y")+I(plaza,"height");y++)for(int x=I(plaza,"x");x<I(plaza,"x")+I(plaza,"width");x++)if(Text(At(layer,y*w+x))!="civic")errors.Add("praça fora da zona cívica");
    }
    static (HashSet<string> expanded,HashSet<string> doors) Buildings(JsonObject map,Dictionary<string,JsonNode> roads,Dictionary<string,JsonNode> catalog,List<string> errors)
    {
        int w=I(map,"width"),h=I(map,"height");var buildings=Items(map["buildings"]);var occupied=new Dictionary<string,string>();var expanded=new HashSet<string>();var doors=new HashSet<string>();var entrances=new HashSet<string>();var props=Items(map["props"]).Select(Key).ToHashSet();
        foreach(var b in buildings)
        {
            string id=S(b,"id"),zone=S(b,"zone"),orientation=S(b,"orientation"),type=S(b,"type");int x=I(b,"x"),y=I(b,"y"),bw=I(b,"width"),bh=I(b,"height");bool rotated=orientation is "east" or "west";catalog.TryGetValue(S(b,"assetId"),out var model);if(model==null||S(model,"biome")!=S(map["settings"],"biome")||b["variant"]==null||I(model,"variant")!=I(b,"variant")||bw!=I(model["footprint"],rotated?"height":"width")||bh!=I(model["footprint"],rotated?"width":"height"))errors.Add($"catálogo divergente em {id}");
            if(b["entrance"] is not JsonNode entrance||new[]{"x","y","level"}.Any(k=>!Finite(entrance[k]))||b["accessPath"] is not JsonArray path||path.Count<2)errors.Add($"acesso 3D ausente em {id}");if(x<0||y<0||x+bw>w||y+bh>h){errors.Add($"edifício {id} fora do mapa");continue;}
            var door=b["door"];if(!InBounds(door,w,h))errors.Add($"porta de {id} fora do mapa");else{string key=Key(door);if(!roads.TryGetValue(key,out var road))errors.Add($"porta de {id} não acessa uma rua");else if(B(road,"bridge"))errors.Add($"porta de {id} usa uma ponte");if(Text(At(map["terrain"],I(door,"y")*w+I(door,"x")))=="water")errors.Add($"porta de {id} está na água");int dx=I(door,"x"),dy=I(door,"y"),gap=zone=="civic"?2:0;var sides=new Dictionary<string,bool>{{"north",dy==y-1-gap&&dx>=x&&dx<x+bw},{"south",dy==y+bh+gap&&dx>=x&&dx<x+bw},{"west",dx==x-1-gap&&dy>=y&&dy<y+bh},{"east",dx==x+bw+gap&&dy>=y&&dy<y+bh}};if(!sides.GetValueOrDefault(orientation)||sides.Values.Count(v=>v)!=1)errors.Add($"porta de {id} não corresponde à orientação");if(b["entranceVisible"]==null||B(b,"entranceVisible")!=(orientation is "south" or "east"))errors.Add($"visibilidade da entrada incorreta em {id}");string ek=$"{D(b["entrance"],"x")}:{D(b["entrance"],"y")}";if(!entrances.Add(ek))errors.Add($"entrada física compartilhada em {ek}");doors.Add(key);}
            string[] allowed=type switch{"house"=>["residential","agricultural","craft","commercial"],"inn" or "shop" or "market"=>["commercial"],"smithy"=>["craft"],"mill"=>["craft","agricultural"],"hall" or "chapel" or "tower"=>["civic"],_=>[]};if(!allowed.Contains(zone))errors.Add($"zona inadequada em {id}: {zone}");if(S(b,"architecture")=="")errors.Add($"arquitetura ausente em {id}");if(Text(At(map["zoneMap"],(y+(bh-1)/2)*w+x+(bw-1)/2))!=zone)errors.Add($"zona do edifício {id} diverge da camada");int zoneCells=0;
            for(int py=y;py<y+bh;py++)for(int px=x;px<x+bw;px++){int i=py*w+px;string key=Key(px,py);if(Text(At(map["zoneMap"],i))==zone)zoneCells++;if(occupied.TryGetValue(key,out var owner))errors.Add($"sobreposição entre {id} e {owner}");occupied[key]=id;if(Text(At(map["terrain"],i))=="water")errors.Add($"{id} construído sobre água");if(Number(At(map["heightLevel"],i))!=D(b,"baseLevel"))errors.Add($"base desnivelada em {id}");}if(zoneCells<Math.Ceiling(bw*bh*.6))errors.Add($"footprint de {id} fora da zona declarada");for(int py=y-1;py<=y+bh;py++)for(int px=x-1;px<=x+bw;px++)expanded.Add(Key(px,py));
        }
        foreach(var b in buildings)
        {
            string id=S(b,"id"),orientation=S(b,"orientation");int x=I(b,"x"),y=I(b,"y"),bw=I(b,"width"),bh=I(b,"height");if(b["door"]!=null&&occupied.ContainsKey(Key(b["door"])))errors.Add($"porta de {id} está dentro de um footprint");if(S(b,"zone")=="residential")foreach(var other in buildings){if(ReferenceEquals(b,other))continue;int ox=I(other,"x"),oy=I(other,"y"),ow=I(other,"width"),oh=I(other,"height");bool touches=orientation is "north" or "south"?y<oy+oh&&oy<y+bh&&(x+bw==ox||ox+ow==x):x<ox+ow&&ox<x+bw&&(y+bh==oy||oy+oh==y);if(touches)errors.Add($"intervalo lateral residencial insuficiente em {id}");}
            if(catalog.TryGetValue(S(b,"assetId"),out var model)&&b["entrance"] is JsonNode entrance){double angle=orientation switch{"south"=>0,"east"=>Math.PI/2,"north"=>Math.PI,"west"=>-Math.PI/2,_=>double.NaN},mx=Number(model["entrance"]?[0]),my=Number(model["entrance"]?[1]),mz=Number(model["entrance"]?[2]);if(Math.Abs(x+bw/2.0+mx*Math.Cos(angle)+mz*Math.Sin(angle)-D(entrance,"x"))>1e-6||Math.Abs(y+bh/2.0-mx*Math.Sin(angle)+mz*Math.Cos(angle)-D(entrance,"y"))>1e-6||Math.Abs(D(b,"baseLevel")+my/.25-D(entrance,"level"))>1e-6)errors.Add($"entrada diverge do modelo em {id}");}
            var path=Items(b["accessPath"]);if(path.Count<2)continue;if(Distance(path[0],b["entrance"])>1e-6||Distance(path[^1],b["door"],.5)>1e-6)errors.Add($"extremos do acesso inválidos em {id}");for(int part=1;part<path.Count;part++){var start=path[part-1];var end=path[part];if(!Finite(start["x"])||!Finite(start["y"])||!Finite(end["x"])||!Finite(end["y"])){errors.Add($"acesso não finito em {id}");break;}double distance=Distance(start,end);if(distance*4>w*h){errors.Add($"acesso fora de escala em {id}");break;}int steps=Math.Max(1,(int)Math.Ceiling(distance*4));for(int step=0;step<=steps;step++){int px=(int)Math.Floor(D(start,"x")+(D(end,"x")-D(start,"x"))*step/steps),py=(int)Math.Floor(D(start,"y")+(D(end,"y")-D(start,"y"))*step/steps);string key=Key(px,py);if(px<0||py<0||px>=w||py>=h||Text(At(map["terrain"],py*w+px))=="water"||(occupied.TryGetValue(key,out var owner)&&owner!=id)||props.Contains(key)){errors.Add($"acesso bloqueado em {id}");break;}}}
        }
        return(expanded,doors);
    }
    static void Urban(JsonObject map,Dictionary<string,JsonNode> roadAt,List<string> errors)
    {
        if(map["roadSegments"] is not JsonArray||map["frontages"] is not JsonArray||map["lots"] is not JsonArray){errors.Add("camadas cadastrais v4 ausentes");return;}int w=I(map,"width"),h=I(map,"height");var segments=new Dictionary<string,JsonNode>();
        foreach(var s in Items(map["roadSegments"])){string id=S(s,"id");if(id==""||!segments.TryAdd(id,s)){errors.Add("segmento viário duplicado ou sem id");continue;}var indexes=Items(s["roadIndexes"]);if(S(s,"axis") is not("ew" or "ns")||s["roadIndexes"] is not JsonArray||I(s,"length")!=indexes.Count)errors.Add($"segmento inválido em {id}");foreach(var i in indexes){var r=At(map["roads"],(int)Number(i));if(r==null||B(r,"bridge")||S(r,"kind")=="plaza")errors.Add($"rua inválida em {id}");else{if(I(r,"connections")!=(S(s,"axis")=="ew"?10:5))errors.Add($"curva ou junção incluída em {id}");if(!Items(r["segmentIds"]).Any(n=>Text(n)==id))errors.Add($"ligação reversa ausente em {id}");}}}
        var frontages=new Dictionary<string,JsonNode>();foreach(var f in Items(map["frontages"])){string id=S(f,"id");if(id==""||!frontages.TryAdd(id,f)){errors.Add("fachada duplicada ou sem id");continue;}segments.TryGetValue(S(f,"segmentId"),out var segment);string[] sides=S(segment,"axis")=="ew"?["north","south"]:["west","east"];var indexes=Items(f["roadIndexes"]);if(segment==null||!sides.Contains(S(f,"side"))||f["roadIndexes"] is not JsonArray||I(f,"length")!=indexes.Count)errors.Add($"fachada inválida em {id}");if(!ZoneTypes.Contains(S(f,"zone")))errors.Add($"zona de fachada inválida em {id}");foreach(var i in indexes)if(!ContainsIndex(segment?["roadIndexes"],(int)Number(i)))errors.Add($"faixa fora do segmento em {id}");}
        var buildings=Items(map["buildings"]);var byBuilding=ById(buildings);var lots=new Dictionary<string,JsonNode>();var occupied=new Dictionary<string,string>();
        foreach(var lot in Items(map["lots"])){string id=S(lot,"id"),zone=S(lot,"zone");if(id==""||!lots.TryAdd(id,lot)){errors.Add("lote duplicado ou sem id");continue;}frontages.TryGetValue(S(lot,"frontageId"),out var frontage);byBuilding.TryGetValue(S(lot,"buildingId"),out var building);if(frontage==null||S(frontage,"zone")!=zone||building==null||S(building,"zone")!=zone)errors.Add($"vínculos inválidos em {id}");if(!Integer(lot["roadIndex"])||!ContainsIndex(frontage?["roadIndexes"],I(lot,"roadIndex")))errors.Add($"acesso inválido em {id}");var cells=Items(lot["cells"]);if(cells.Count==0){errors.Add($"células ausentes em {id}");continue;}foreach(var cell in cells){if(!InBounds(cell,w,h)){errors.Add($"célula fora do mapa em {id}");continue;}string key=Key(cell);if(occupied.TryGetValue(key,out var owner))errors.Add($"sobreposição entre {id} e {owner}");occupied[key]=id;int i=I(cell,"y")*w+I(cell,"x");if(Text(At(map["terrain"],i))=="water")errors.Add($"lote molhado em {id}");if(Text(At(map["zoneMap"],i))!=zone)errors.Add($"lote fora do distrito em {id}");}}
        foreach(var b in buildings)
        {
            string id=S(b,"id"),zone=S(b,"zone"),orientation=S(b,"orientation");lots.TryGetValue(S(b,"lotId"),out var lot);if(lot==null||S(lot,"frontageId")!=S(b,"frontageId")||S(lot,"buildingId")!=id)errors.Add($"edifício sem lote/fachada em {id}");var cells=Items(lot?["cells"]).Select(Key).ToHashSet();int x=I(b,"x"),y=I(b,"y"),width=I(b,"width"),height=I(b,"height");for(int py=y;py<y+height;py++)for(int px=x;px<x+width;px++)if(!cells.Contains(Key(px,py)))errors.Add($"footprint fora do lote em {id}");var door=b["door"];if(!roadAt.TryGetValue(Key(door),out var access)||B(access,"bridge")||I(access,"connections") is not(5 or 10))errors.Add($"porta em curva, junção ou ponte em {id}");foreach(var d in Directions)if(roadAt.TryGetValue(Key(I(door,"x")+d.dx,I(door,"y")+d.dy),out var n)&&(B(n,"bridge")||S(n,"kind")=="plaza"||I(n,"connections") is not(5 or 10)))errors.Add($"buffer viário insuficiente em {id}");int rear=zone switch{"residential"=>1,"agricultural"=>3,"craft" or "civic"=>2,_=>0};if(lot==null||I(lot,"rearDepth")<rear)errors.Add($"pátio insuficiente em {id}");int lateral=zone=="commercial"?0:zone=="civic"?2:1,front=zone=="civic"?2:0,leading=zone=="civic"?lateral:0;if(orientation is "north" or "south"){x-=leading;width+=leading+lateral;height+=rear+front;y-=orientation=="south"?rear:front;}else{y-=leading;height+=leading+lateral;width+=rear+front;x-=orientation=="east"?rear:front;}for(int py=y;py<y+height;py++)for(int px=x;px<x+width;px++)if(!cells.Contains(Key(px,py)))errors.Add($"geometria de pátio insuficiente em {id}");var bounds=lot?["bounds"];if(bounds==null||I(bounds,"x")!=x||I(bounds,"y")!=y||I(bounds,"width")!=width||I(bounds,"height")!=height||cells.Count!=width*height)errors.Add($"bounds de lote divergentes em {id}");
        }
    }
}
